services:
  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - ./server/seed.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - app_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
  nuxt:
    build:
      dockerfile: Dockerfile
      context: ./client
    image: nuxt_dev
    container_name: nuxt_dev
    command: npm run dev
    ports:
      - '3000:3000'
volumes:
  app_data:
