services:
    postgres:
        build:
            context: .
            dockerfile: Dockerfile
        image: 'postgres'
        container_name: 'postgres-dev'
        environment:
            POSTGRES_PASSWORD: 'password'
        volumes:
            - dbvol:/data/postgres-vol
        ports:
            - '5432:5432'
        restart: unless-stopped
volumes:
    dbvol:
